responses = [
    "可爸爸的十环那么厉害，你是怎么打败他的？",
    "那你现在还有魔法吗？",
    "Okay.",
    "Hello, sir, welcome to the Fairmont…",
    "No, you're not… Katy.",
    "Hey, hey, get back here.",
    "Give me the key.",
    "(SIGHS) Please open the door.",
    "Get out.",
    "Look, if happens to this thing, we're gonna be jobless and in debt for the rest of our lives.",
    "I don't know who that is.",
    "Please get out of the car.",
    "(GASPS) Katy, watch the…",
    "I knew Katy was trouble the first day we met in high school.",
    "I was getting picked on a lot, for all the reasons we all get picked on a lot.",
    "Plus, I had just moved to the US, so I was struggling with my English, and I was on my way to lunch one day when this guy who was like twice my size yells at me from down the hall, “What's up, Gangnam Style?”",
    "So I yelled back, “I'm not Korean, idiot.”",
    "And right before he was about to throw the first punch,",
    "Katy comes out of nowhere, steps right between us and starts screaming the lyrics to Hotel California.",
    "And that's how we met.",
    "At which point she revealed that she had also swiped the keys to the guy's Mustang."
    "That's true. You were.",
    "That's still a part of the car.",
    "Yeah, what's that supposed to mean?",
    "Wow.",
    "Yeah, that doesn't even make any sense.",
    "It's like the most challenging job ever.",
    "You need people skills, driving skills…",
    "Well, it's almost midnight. We got the early shift.",
    "Should probably be responsible, go to sleep.",
    "Morning, Mrs Chen.",
    "I'm happy to help.",
    "Waipo.",
    "Oh, sorry.",
    "Are you sure that Waigong's allowed to take",
    "Funyuns and cigarettes back to the afterlife?",
    "She really likes her job.",
    "We both do.",
    "Mm.",
    "走了，外婆。",
    "外婆我们只是朋友。",
    "So?",
    "I'm sorry about her.",
    "How's it goin'?",
    "I don't know what you're talking about, dude.",
    "Hey! Get off of me!",
    "我不想惹麻烦。",
    "You okay?",
    "Sorry.",
    "You really wanna talk about this now?",
    "Open the door, please!",
    "The back is about to go.",
    "On my signal, make a hard right."
    "Everybody to the front now!",
    "Oh, God.",
    "Macau.",
    "Those guys are going after my sister next, and I have to get to her first.",
    "Look, I know this is confusing."
    "I'll explain it when I get back, I promise.",
    "My sister sent me this a few months ago.",
    "I think it's the address of where she's staying.",
    "Those guys back there were sent by my dad.",
    "If they hurt her…",
    "I'm sorry, but I have to go.",
    "What? No, Katy, you can't just…",
    "After my mom died… my dad started my training.",
    "From sunup to sundown, I was taught every possible way to kill a man.",
    "By the time I was 14, I could barely remember what life was like before she died.",
    "That's how old I was when he sent me on my first assignment.",
    "I was willing to do anything he wanted.",
    "If he asked me to burn the world down, I would've asked him…",
    "Yeah, same.",
    "Beef.",
    "I knew that I couldn't go back to him, so I just… ran.",
    "I know this is a lot to dump on you.",
    "I should also probably mention that my name's not technically Shaun.",
    "It's Shang-Chi.",
    "No. Shang-Chi.",
    "Shang.",
    "Shang.",
    "S-H-A-N-G. Shang.",
    "Yeah.",
    "Yeah, I don't… Yeah.",
    "Okay, I was 15 years old. All right?",
    "Okay.",
    "That's not what happened.",
    "(MOUTHING) Can't hear you. I'm sorry.",
    "我在找我妹，徐夏灵。",
    "你听说过她吗？",
    "这里是她给我的地址。",
    "Okay.",
    "Uh…",
    "Oh, no.",
    "Wait. What?",
    "Think there's been some sort of confusion.",
    "I'm not here to fight anybody. Okay?",
    "I'm looking for my sister, Xu Xialing.",
    "Yeah, look, I'm not going up there, okay?",
    "I'm just trying to…",
    "What?",
    "It doesn't matter.",
    "Thank you.",
    "Yeah.",
    "妹妹。",
    "Wait, wait!",
    "你怎么了你？",
    "我知道你在生我的气。",
    "但是我有急事和你说？",
    "我们没有时间打。",
    "你能不能不打我？",
    "住手!我是来帮你的!",
    "爸要来找你。",
    "我不会再跟你打。",
    "你有。",
    "Mom's dead.",
    "灵灵，我三天以后就回来。",
    "这地方归你管？",
    "Where'd you get all that money?",
    "Did you bet against me?",
    "The Ten Rings ambushed us in San Francisco.",
    "They took my pendant.",
    "They're gonna come for yours next.",
    "I don't know what he wants with them, but we both know it can't be good.",
    "Then why would you send me the postcard?",
    "Is there a back exit?",
    "Hey. Hey! Hey, open up!",
    "Uh…",
    "Come on!",
    "If we make it to the elevator, we can hop in on the next floor.",
    "Katy, we're out of options. We have to go now.",
    "One, two, three.",
    "Just head straight for that elevator.",
    "You got this.",
    "I'll buy you some time. Just keep going.",
    "I'm coming!",
    "Hang on.",
    "(STRAINING) Gotcha.",
    "Katy!",
    "你把我们丢在这里说走就走！",
    "What does he want with the pendant…",
    "Yes.",
    "How did you find me?",
    "That's not gonna happen.",
    "Her name is Katy.",
    "To do what?",
    "Dad, Mom's gone.",
    "She's not talking to you from behind a gate, and she's not leaving any clues for us.",
    "What?",
    "You can't just march into our mom's village with this bullshit.",
    "I mean, do you have any idea how insane…",
    "She used to tell us stories about Ta Lo when we were kids.",
    "A village in another dimension full of magical creatures.",
    "I thought it was just a fairy tale.",
    "About Mom being locked behind a gate by her own people?",
    "Look, I don't know what the hell is going on, but if we don't find a way to get to Ta Lo before him, he's gonna destroy everything that's left of our family.",
    "The hell was that?",
    "Then my dad broke you out?",
    "To kill you.",
    "Uh, thank you, Trevor. I think we're okay.",
    "Right now, we really just need to find a way to…",
    "What the hell?",
    "What is that?",
    "That! That! That!",
    "How would he know me?",
    "Believe me, buddy, I would if I knew how.",
    "According to my dad, the path there only opens once a year.",
    "How did you…",
    "Just head up that ramp and through the front gate.",
    "Should be a straight shot.",
    "Figure we got about 30 seconds until he…",
    "Incoming!",
    "Doing my best.",
    "I'm trying!",
    "So you became an actor because you thought the monkeys were actually…",
    "Um, this is really cool and all, but how long do we have to sit here?",
    "Okay, but how long are we talking?",
    "Like, hours? Days?",
    "Katy, go, go, go!",
    "Hard right where?",
    "What happens if we don't stay in the pocket?",
    "Eats us? What does that mean?",
    "Watch your back!",
    "Really fricking close.",
    "大家好！",
    "我是徐尚气。",
    "这是我的妹妹，徐夏灵。",
    "我们是映丽的孩子。",
    "这是我的朋友，凯蒂。",
    "你误会了。请听我们说。",
    "Whoa.",
    "We don't have much time.",
    "Our father is coming.",
    "Our dad is coming here to open that gate.",
    "He thinks you're holding our mom there.",
    "He hasn't taken them off since she died.",
    "What do they have to do with all this?",
    "So you think soul eaters are talking to our dad?",
    "Oh, you're gonna deliver some dragon arrows?",
    "My mother was the only one who could beat him.",
    "Show me how she did it.",
    "可是你现在没有魔法了呀。",
    "妈妈。",
    "妈妈。",
    "爸爸。",
    "I'm not who you think I am.",
    "That's not what I'm talking about.",
    "When my dad sent me to find the man who killed my mom…",
    "I told you I couldn't go through with it.",
    "I lied.",
    "I thought that I could change my name, start a new life, pretend like it never happened.",
    "But…",
    "She would hate the person I've become.",
    "My mom is dead because of him.",
    "And now he's coming to destroy her home.",
    "血债必须要血偿。",
    "I'm gonna do what he trained me to do.",
    "I'm gonna kill him.",
    "I'm not afraid of you.",
    "She was gone and we needed you.",
    "But you chose those damn rings over us. (SNIFFLES)",
    "You trained your son to be a killer.",
    "Is this what you wanted?",
    "Even if you could bring her back,",
    "what makes you think she'd want anything to do with you?",
    "She's not back there, Dad.",
    "No.",
    "I wish that were true.",
    "Dad, please.",
    "Your family needs you.",
    "Shit.",
    "It's headed for the village!",
    "I'm not leaving you again.",
    "爸，一路走好。",
    "And I'm hanging on to The Great Protector with my sister at this point, trying not to get eaten by the Mega Soul Sucker.",
    "Yeah. It was trying to eat our dragon's soul.",
    "Yeah.",
    "She hit it dead on.",
    "Yeah, we, uh, lost some good people that day… but we made it.",
    "We made it.",
    "She's back at my dad's compound, shutting down his operations.",
    "Uh… Here.",
    "Present.",
    "Yeah, I know, sir. I'm a huge fan…",
    "Uh… Yeah, yes.",
    "I think we should…",
    "Uh, we gotta go.",
    "I'll Venmo you for the…",
    "Um…",
    "About a thousand years.",
    "A message to where?",
    "Yeah. Yeah, we probably should do that.",
    "Or…",
]
